package com.past9.phoneaos.system

import android.content.ComponentName
import android.content.Context
import android.content.pm.PackageManager

/**
 * The user's character IS the app: its launcher icon and notification glyph follow the mascot
 * and colour they picked. Icons are activity-aliases generated by IconGen (one per mascot x colour).
 */
object Identity {
    /** The character as a picture: their colour's soft background, the mascot shape, two eyes. */
    fun avatar(context: Context, mascot: String, accent: String, px: Int = 192): android.graphics.Bitmap {
        val a = com.past9.phoneaos.ui.theme.accentOf(accent)
        fun argb(c: androidx.compose.ui.graphics.Color) = android.graphics.Color.argb((c.alpha * 255).toInt(), (c.red * 255).toInt(), (c.green * 255).toInt(), (c.blue * 255).toInt())
        val bmp = android.graphics.Bitmap.createBitmap(px, px, android.graphics.Bitmap.Config.ARGB_8888)
        val cv = android.graphics.Canvas(bmp)
        val paint = android.graphics.Paint(android.graphics.Paint.ANTI_ALIAS_FLAG)
        paint.color = argb(a.lPC); cv.drawCircle(px / 2f, px / 2f, px / 2f, paint)
        val poly = com.past9.phoneaos.ui.mascotOf(mascot).rest.normalized()
        val path = android.graphics.Path().also { p -> poly.cubics.forEachIndexed { i, c -> if (i == 0) p.moveTo(c.anchor0X, c.anchor0Y); p.cubicTo(c.control0X, c.control0Y, c.control1X, c.control1Y, c.anchor1X, c.anchor1Y) }; p.close() }
        val m = android.graphics.Matrix(); val size = px * 0.62f; val off = (px - size) / 2f
        m.setScale(size, size); m.postTranslate(off, off); path.transform(m)
        paint.color = argb(a.lP); cv.drawPath(path, paint)
        paint.color = argb(a.lOnP)
        val ew = px * 0.075f; val eh = px * 0.12f; val gap = px * 0.085f
        cv.drawRoundRect(px / 2f - gap - ew, px / 2f - eh / 2, px / 2f - gap, px / 2f + eh / 2, ew, ew, paint)
        cv.drawRoundRect(px / 2f + gap, px / 2f - eh / 2, px / 2f + gap + ew, px / 2f + eh / 2, ew, ew, paint)
        return bmp
    }

    /**
     * Notifications show the agent as a conversation partner, so phones that put an avatar on the
     * left (Samsung) show the user's character instead of the app's stock icon.
     */
    fun publishAgentShortcut(context: Context, name: String, mascot: String, accent: String): androidx.core.app.Person {
        val icon = androidx.core.graphics.drawable.IconCompat.createWithAdaptiveBitmap(avatar(context, mascot, accent, 216))
        val person = androidx.core.app.Person.Builder().setName(name).setIcon(icon).setBot(true).setKey("agent").setImportant(true).build()
        runCatching {
            // A shortcut must belong to a launcher activity. MainActivity isn't one (the icon aliases are),
            // so without naming the live alias Android rejected it and Samsung fell back to the stock icon.
            val sc = androidx.core.content.pm.ShortcutInfoCompat.Builder(context, "agent").setShortLabel(name).setLongLived(true).setPerson(person).setIcon(icon)
                .setActivity(launcherAlias(context))
                .setIntent(android.content.Intent(context, com.past9.phoneaos.MainActivity::class.java).setAction(android.content.Intent.ACTION_VIEW).putExtra("open", "chat")).build()
            androidx.core.content.pm.ShortcutManagerCompat.pushDynamicShortcut(context, sc)
        }.onFailure { android.util.Log.w("Identity", "agent shortcut rejected", it) }
        return person
    }

    /**
     * Android won't rename an installed app, so the closest thing: a home-screen shortcut carrying
     * the agent's own name and face (e.g. "Hina", red ghost) that opens straight into the app.
     */
    fun pinNamedShortcut(context: Context, name: String, mascot: String, accent: String): Boolean {
        if (!androidx.core.content.pm.ShortcutManagerCompat.isRequestPinShortcutSupported(context)) return false
        val sc = androidx.core.content.pm.ShortcutInfoCompat.Builder(context, "home-$name").setShortLabel(name).setLongLabel(name)
            .setIcon(androidx.core.graphics.drawable.IconCompat.createWithAdaptiveBitmap(avatar(context, mascot, accent, 216)))
            .setIntent(android.content.Intent(context, com.past9.phoneaos.MainActivity::class.java).setAction(android.content.Intent.ACTION_MAIN)).build()
        return androidx.core.content.pm.ShortcutManagerCompat.requestPinShortcut(context, sc, null)
    }

    /** The icon alias that is enabled right now: the app's real launcher entry. */
    fun launcherAlias(context: Context): ComponentName {
        val pm = context.packageManager
        return pm.queryIntentActivities(android.content.Intent(android.content.Intent.ACTION_MAIN).addCategory(android.content.Intent.CATEGORY_LAUNCHER).setPackage(context.packageName), 0)
            .firstOrNull()?.activityInfo?.let { ComponentName(context.packageName, it.name) }
            ?: ComponentName(context, "${context.packageName}.Icon_scout_iris")
    }

    /**
     * Every notification speaks as the agent: a one-message conversation from the agent's Person, tied to
     * the agent shortcut. Samsung and Pixel then draw the agent's own face where the app icon would go.
     */
    fun asAgent(context: Context, b: androidx.core.app.NotificationCompat.Builder, title: String, body: String): androidx.core.app.NotificationCompat.Builder {
        val st = com.past9.phoneaos.App.graph(context).settings.state.value
        val agent = publishAgentShortcut(context, st.agentName.ifBlank { "Your agent" }, st.mascot, st.accent)
        val me = androidx.core.app.Person.Builder().setName(st.userName.ifBlank { "You" }).setKey("me").build()
        return b.setStyle(androidx.core.app.NotificationCompat.MessagingStyle(me).addMessage(if (title.isBlank()) body else "$title\n$body", System.currentTimeMillis(), agent))
            .setShortcutId("agent").setLargeIcon(avatar(context, st.mascot, st.accent, 192)).setCategory(androidx.core.app.NotificationCompat.CATEGORY_MESSAGE)
    }

    fun statIcon(context: Context, mascot: String): Int =
        context.resources.getIdentifier("ic_stat_$mascot", "drawable", context.packageName).takeIf { it != 0 } ?: com.past9.phoneaos.R.drawable.ic_stat_agent

    /** Switch the home-screen icon. Call when the app goes to the background, never mid-use. */
    fun applyLauncherIcon(context: Context, mascot: String, accent: String) {
        val pm = context.packageManager
        val want = ComponentName(context, "${context.packageName}.Icon_${mascot}_$accent")
        val enabled = runCatching { pm.getComponentEnabledSetting(want) }.getOrNull() ?: return
        if (enabled == PackageManager.COMPONENT_ENABLED_STATE_ENABLED) return
        val aliases = pm.getPackageInfo(context.packageName, PackageManager.GET_ACTIVITIES or PackageManager.MATCH_DISABLED_COMPONENTS).activities.orEmpty()
            .map { it.name }.filter { it.contains(".Icon_") }
        if (want.className !in aliases) return
        pm.setComponentEnabledSetting(want, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP)
        aliases.filter { it != want.className }.forEach {
            pm.setComponentEnabledSetting(ComponentName(context, it), PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP)
        }
    }
}
